# Generated by Django 4.2.3 on 2023-07-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photo',
            field=models.ImageField(height_field=500, upload_to='', width_field=500),
        ),
    ]
