# Generated by Django 4.2.3 on 2023-07-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_record_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photo',
            field=models.ImageField(height_field=500, upload_to='website/files/', width_field=500),
        ),
    ]
